version: '2'
services:
  web:
    build: .
    ports:
    - '80:80'
    links:
    - db:db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - '4040:80'
    links:
    - db:db
  db:
    image: dnhsoft/mysql-utf8
    ports:
    - '3306:3306'
    environment:
      MYSQL_DATABASE: film_db
      MYSQL_USER: pl_bru
      MYSQL_PASSWORD: mamene
      MYSQL_ROOT_PASSWORD: toimemetusaismamene
