version: '3'
services:
  web:
    build: .
    ports:
    - "8080:80"
    links:
    - db:db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "4040:80"
    links:
    - db:db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mamene
